-- ========================================
-- Organization Table
-- ========================================
CREATE TABLE organization (
    organization_id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    logo_filename VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS service_project (
    service_project_id INT GENERATED BY DEFAULT AS IDENTITY,
    organization_id INT NOT NULL,
    service_project_title VARCHAR(150) NOT NULL,
    service_project_description TEXT NOT NULL,
    service_project_location VARCHAR(255) NOT NULL,
    service_project_date DATE NOT NULL,
    CONSTRAINT service_project_pk PRIMARY KEY (service_project_id),
    CONSTRAINT fk_organization FOREIGN KEY (organization_id)
        REFERENCES public.organization (organization_id)
        ON DELETE CASCADE
);

-- Insert 15 sample service projects distributed across 3 organizations
INSERT INTO public.service_project (organization_id, service_project_title, service_project_description, service_project_location, service_project_date) VALUES
-- Organization 1 Projects
(1, 'Building Chicken Coops', 'Built sturdy chicken coops for local families and small farms to provide safe shelter for poultry and support sustainable food production.', 'Cedar City Community Farm', '2026-03-15'),
(1, 'Sanding Park Benches', 'Sanded and prepared aging park benches for repainting, helping improve the appearance and safety of local parks.', 'Main Street Park', '2026-04-05'),
(1, 'Repainting Cemetery Fences', 'Cleaned, primed, and repainted cemetery fences to preserve the grounds and honor the community''s history.', 'Cedar City Cemetery', '2026-05-10'),
(1, 'Refurbishing Park Trash Cans', 'Restored weathered park trash cans with fresh paint and repairs to improve cleanliness and appearance.', 'Canyon Park', '2026-06-07'),
(1, 'Building Book Donation Boxes', 'Constructed and installed community book-sharing boxes to encourage literacy and neighborhood engagement.', 'Cedar City Public Library', '2026-07-19'),

-- Organization 2 Projects
(2, 'Tending to Chicken Hatcheries', 'Assisted hatchery staff with feeding, cleaning, and maintaining healthy environments for young chicks.', 'Iron County Hatchery', '2026-03-22'),
(2, 'Tending Local Gardens', 'Helped plant, weed, water, and maintain community gardens that provide fresh produce for local residents.', 'Heritage Community Garden', '2026-04-19'),
(2, 'Building Pollinator Habitats', 'Created pollinator-friendly habitats by planting native flowers and assembling bee and butterfly shelters.', 'Three Peaks Recreation Area', '2026-05-24'),
(2, 'Farrier Work Assistance', 'Assisted experienced farriers by preparing equipment, handling horses, and maintaining safe working areas.', 'Cedar Ridge Ranch', '2026-06-14'),
(2, 'Sheep Shearing Assistance', 'Supported local ranchers during sheep shearing by organizing wool, assisting with livestock handling, and cleaning work areas.', 'Parowan Valley Ranch', '2026-07-10'),

-- Organization 3 Projects
(3, 'Hospital Visits', 'Visited patients to provide companionship, conversation, and encouragement while delivering small care packages.', 'Cedar City Hospital', '2026-03-29'),
(3, 'Egg Deliveries to Food Shelters', 'Collected and delivered fresh eggs from local farms to food shelters, helping provide nutritious meals to families in need.', 'Iron County Food Pantry', '2026-04-26'),
(3, 'Volunteer at the Bishop Storehouse', 'Assisted with organizing inventory, stocking shelves, and preparing food orders for families in need.', 'Bishop''s Storehouse', '2026-05-17'),
(3, 'Community Clothing Drive', 'Collected, sorted, and organized donated clothing for distribution to individuals and families facing financial hardship.', 'Cedar City Community Center', '2026-06-21'),
(3, 'Write Get Well Soon Cards', 'Created heartfelt cards with encouraging messages to brighten the days of patients recovering from illness or injury.', 'Community Service Center', '2026-07-26');


-- ========================================
-- Insert sample data: Organizations
-- ========================================
INSERT INTO organization (name, description, contact_email, logo_filename)
VALUES 
(
    'BrightFuture Builders', 
    'A nonprofit focused on improving community infrastructure through sustainable construction projects.', 
    'info@brightfuturebuilders.org', 
    'brightfuture-logo.png'
),
(
    'GreenHarvest Growers', 
    'An urban farming collective promoting food sustainability and education in local neighborhoods.', 
    'contact@greenharvest.org', 
    'greenharvest-logo.png'
),
(
    'UnityServe Volunteers', 
    'A volunteer coordination group supporting local charities and service initiatives.', 
    'hello@unityserve.org', 
    'unityserve-logo.png'
);